name: Tuya MQTT Doorbell
version: "1.0"
slug: tuya_mqtt_doorbell
description: Integration for Tuya doorbell via MQTT
arch:
  - amd64
  - armv7
  - armhf
startup: application
boot: auto

schema:
  mqtt_broker:
    type: str
  mqtt_port:
    type: int
  mqtt_username:
    type: str
  mqtt_password:
    type: password
  device_id:
    type: str
  device_local_key:
    type: str
