name: Tuya MQTT Doorbell
version: "1.0"
slug: tuya_mqtt_doorbell
description: Integration for Tuya doorbell via MQTT
arch:
  - amd64
  - armv7
  - armhf
startup: application
boot: auto
options:
  mqtt:
    broker: ""
    port: 1883
    username: ""
    password: ""
  device:
    id: ""
    local_key: ""
schema:
  type: object
  properties:
    mqtt:
      type: object
      properties:
        broker:
          type: string
          description: "MQTT broker IP or hostname"
        port:
          type: integer
          description: "MQTT port"
          default: 1883
        username:
          type: string
          description: "MQTT username"
        password:
          type: string
          description: "MQTT password"
      required: [broker, port, username, password]
    device:
      type: object
      properties:
        id:
          type: string
          description: "Tuya device ID"
        local_key:
          type: string
          description: "Tuya device local key"
      required: [id, local_key]
  required: [mqtt, device]
