name: Tuya MQTT Doorbell
version: "1.0"
slug: tuya_mqtt_doorbell
description: Integration for Tuya doorbell via MQTT
arch:
  - amd64
  - armv7
  - armhf
startup: application
boot: auto

options:
  mqtt_broker: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  device_id: ""
  device_local_key: ""

schema:
  mqtt_broker:
    type: str
    description: MQTT broker IP or hostname
  mqtt_port:
    type: int
    description: MQTT port
    default: 1883
  mqtt_username:
    type: str
    description: MQTT username
  mqtt_password:
    type: password
    description: MQTT password
  device_id:
    type: str
    description: Tuya device ID
  device_local_key:
    type: str
    description: Tuya device local key
