name: Tuya MQTT Doorbell
version: "1.0"
slug: tuya_mqtt_doorbell
description: Integration for Tuya doorbell via MQTT
arch:
  - amd64
  - armv7
  - armhf
startup: application
boot: auto
# map: []  # lub usuń całkowicie
options: {}
schema: {}
