name: Tuya MQTT Doorbell
version: "1.0.0"
slug: tuya_mqtt_doorbell
description: Integration for Tuya doorbell via MQTT
arch:
  - amd64
  - armv7
  - aarch64
  - armhf
  - i386
startup: application
boot: auto
init: false
options:
  mqtt_broker: ""
  mqtt_port: "1883"
  mqtt_username: ""
  mqtt_password: ""
  device_id: ""
  device_local_key: ""
schema:
  mqtt_broker: str
  mqtt_port: str
  mqtt_username: str
  mqtt_password: password
  device_id: str
  device_local_key: str
